-- Run this in PRODUCTION Supabase SQL Editor
-- This creates the exact table structure from development

-- Drop existing wrong tables
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS contracts CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;

-- Create CLIENTS table (exact match for development)
CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    phone VARCHAR,
    address TEXT,
    notes TEXT,
    total_bookings INTEGER DEFAULT 0,
    total_revenue NUMERIC(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    booking_ids TEXT
);

-- Create BOOKINGS table (exact match for development)
CREATE TABLE bookings (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    client_name VARCHAR NOT NULL,
    client_email VARCHAR,
    client_phone VARCHAR,
    event_date TIMESTAMP,
    event_time VARCHAR,
    event_end_time VARCHAR,
    performance_duration TEXT,
    venue VARCHAR,
    event_type VARCHAR,
    gig_type VARCHAR,
    estimated_value VARCHAR,
    status VARCHAR DEFAULT 'new' NOT NULL,
    notes TEXT,
    original_email_content TEXT,
    apply_now_link VARCHAR,
    response_needed BOOLEAN DEFAULT true,
    last_contacted_at TIMESTAMP,
    has_conflicts BOOLEAN DEFAULT false,
    conflict_count INTEGER DEFAULT 0,
    conflict_details TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    previous_status VARCHAR,
    contract_sent BOOLEAN DEFAULT false,
    contract_signed BOOLEAN DEFAULT false,
    invoice_sent BOOLEAN DEFAULT false,
    paid_in_full BOOLEAN DEFAULT false,
    deposit_paid BOOLEAN DEFAULT false,
    quoted_amount NUMERIC(10,2),
    deposit_amount NUMERIC(10,2),
    final_amount NUMERIC(10,2),
    completed BOOLEAN DEFAULT false,
    venue_address TEXT,
    client_address TEXT,
    equipment_requirements TEXT,
    special_requirements TEXT,
    fee NUMERIC(10,2),
    styles TEXT,
    equipment_provided TEXT,
    whats_included TEXT,
    uploaded_contract_url TEXT,
    uploaded_contract_key TEXT,
    uploaded_contract_filename VARCHAR,
    uploaded_invoice_url TEXT,
    uploaded_invoice_key TEXT,
    uploaded_invoice_filename VARCHAR,
    uploaded_documents JSONB DEFAULT '[]',
    travel_expense NUMERIC(10,2),
    venue_contact TEXT,
    sound_tech_contact TEXT,
    stage_size VARCHAR(50),
    power_equipment TEXT,
    dress_code VARCHAR(255),
    style_mood VARCHAR(50),
    must_play_songs TEXT,
    avoid_songs TEXT,
    set_order VARCHAR(50),
    first_dance_song VARCHAR(255),
    processional_song VARCHAR(255),
    signing_register_song VARCHAR(255),
    recessional_song VARCHAR(255),
    special_dedications TEXT,
    guest_announcements TEXT,
    load_in_info TEXT,
    sound_check_time VARCHAR(50),
    weather_contingency TEXT,
    parking_permit_required BOOLEAN DEFAULT false,
    meal_provided BOOLEAN DEFAULT false,
    dietary_requirements TEXT,
    shared_notes TEXT,
    reference_tracks TEXT,
    photo_permission BOOLEAN DEFAULT false,
    encore_allowed BOOLEAN DEFAULT false,
    encore_suggestions VARCHAR(255),
    venue_contact_info TEXT,
    parking_info TEXT,
    contact_phone TEXT,
    what3words VARCHAR,
    email_hash VARCHAR,
    processed_at TIMESTAMP,
    field_locks JSONB DEFAULT '{}',
    document_url TEXT,
    document_key TEXT,
    document_name TEXT,
    document_uploaded_at TIMESTAMP,
    distance TEXT,
    distance_value INTEGER,
    duration TEXT,
    collaboration_token VARCHAR,
    collaboration_token_generated_at TIMESTAMP,
    workflow_stage VARCHAR(50) DEFAULT 'initial',
    map_static_url TEXT,
    map_latitude NUMERIC(10,7),
    map_longitude NUMERIC(10,7)
);

-- Create CONTRACTS table (exact match for development)
CREATE TABLE contracts (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    enquiry_id INTEGER NOT NULL,
    contract_number VARCHAR NOT NULL,
    client_name VARCHAR NOT NULL,
    event_date TIMESTAMP NOT NULL,
    event_time VARCHAR NOT NULL,
    venue VARCHAR NOT NULL,
    fee NUMERIC(10,2) NOT NULL,
    status VARCHAR DEFAULT 'pending' NOT NULL,
    signed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    client_email VARCHAR NOT NULL,
    client_phone VARCHAR,
    event_end_time VARCHAR,
    reminder_enabled BOOLEAN DEFAULT true,
    reminder_days INTEGER DEFAULT 3,
    last_reminder_sent TIMESTAMP,
    reminder_count INTEGER DEFAULT 0,
    cloud_storage_url TEXT,
    cloud_storage_key TEXT,
    signing_url_created_at TIMESTAMP,
    venue_address TEXT,
    client_fillable_fields JSONB,
    client_address TEXT,
    payment_instructions TEXT,
    equipment_requirements TEXT,
    special_requirements TEXT,
    deposit NUMERIC(10,2),
    client_signature TEXT,
    sent_at TIMESTAMP,
    signing_page_url TEXT,
    signing_page_key TEXT,
    client_ip_address VARCHAR,
    template VARCHAR DEFAULT 'standard',
    setlist TEXT,
    rider_notes TEXT,
    travel_expenses NUMERIC(10,2) DEFAULT 0.00,
    cancellation_policy TEXT,
    additional_terms TEXT,
    superseded_by INTEGER,
    original_contract_id INTEGER,
    performance_duration TEXT,
    client_portal_url TEXT,
    client_portal_token TEXT,
    client_portal_qr_code TEXT,
    venue_contact TEXT,
    sound_tech_contact TEXT,
    stage_size VARCHAR(50),
    power_equipment TEXT,
    dress_code VARCHAR(255),
    style_mood VARCHAR(50),
    must_play_songs TEXT,
    avoid_songs TEXT,
    set_order VARCHAR(50),
    first_dance_song VARCHAR(255),
    processional_song VARCHAR(255),
    signing_register_song VARCHAR(255),
    recessional_song VARCHAR(255),
    special_dedications TEXT,
    guest_announcements TEXT,
    load_in_info TEXT,
    sound_check_time VARCHAR(50),
    weather_contingency TEXT,
    parking_permit_required BOOLEAN DEFAULT false,
    meal_provided BOOLEAN DEFAULT false,
    dietary_requirements TEXT,
    shared_notes TEXT,
    reference_tracks TEXT,
    photo_permission BOOLEAN DEFAULT false,
    encore_allowed BOOLEAN DEFAULT false,
    encore_suggestions VARCHAR(255),
    deposit_days INTEGER DEFAULT 7
);

-- Create INVOICES table (exact match for development)
CREATE TABLE invoices (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    contract_id INTEGER,
    invoice_number VARCHAR NOT NULL,
    client_name VARCHAR NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    due_date TIMESTAMP NOT NULL,
    status VARCHAR DEFAULT 'pending' NOT NULL,
    paid_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    client_address TEXT,
    event_date TIMESTAMP,
    fee NUMERIC(10,2),
    deposit_paid NUMERIC(10,2) DEFAULT 0.00,
    client_email VARCHAR,
    venue_address TEXT,
    cloud_storage_url TEXT,
    cloud_storage_key TEXT,
    cc_email VARCHAR,
    booking_id INTEGER,
    invoice_theme VARCHAR DEFAULT 'classic',
    share_token VARCHAR,
    stripe_payment_link_id VARCHAR,
    stripe_payment_url TEXT,
    stripe_session_id VARCHAR,
    performance_duration TEXT,
    gig_type VARCHAR,
    invoice_type VARCHAR DEFAULT 'standard',
    description TEXT
);

-- Add constraints
ALTER TABLE contracts ADD CONSTRAINT contracts_contract_number_unique UNIQUE (contract_number);
ALTER TABLE invoices ADD CONSTRAINT invoices_invoice_number_unique UNIQUE (invoice_number);

-- Grant permissions
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

SELECT 'Schema created successfully - ready for data copy!' as status;