-- Fix production database schemas to match development
-- This adds all missing columns to existing tables

-- Fix users table schema
ALTER TABLE users ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_notes TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS additional_hour_rate DECIMAL(10,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_pricing_enabled BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS assigned_by INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS base_hourly_rate DECIMAL(10,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS beta_feedback_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by_admin BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS device_fingerprint TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dj_service_rate DECIMAL(10,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_prefix TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS fraud_score INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_paid BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_assigned BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_beta_tester BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_lifetime BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS minimum_booking_hours INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS quick_add_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reminder_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS settings_completed BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_ip_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS widget_qr_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS widget_url TEXT;

-- Fix user_settings table schema
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS additional_hour_rate DECIMAL(10,2);
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS address_line1 TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS address_line2 TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS ai_pricing_enabled BOOLEAN DEFAULT false;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS bank_details JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS base_hourly_rate DECIMAL(10,2);
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS booking_display_limit INTEGER DEFAULT 50;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS business_contact_email TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS contract_clauses JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS county TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS custom_clauses JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS custom_gig_types JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS custom_invoice_clauses JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS custom_pricing_packages JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS distance_units TEXT DEFAULT 'miles';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS dj_service_rate DECIMAL(10,2);
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS email_from_name TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS email_signature_text TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gig_types JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS home_address_line1 TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS home_address_line2 TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS home_city TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS home_postcode TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS invoice_clauses JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS invoice_payment_terms TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS invoice_prefix TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS local_travel_radius INTEGER DEFAULT 25;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS minimum_booking_hours INTEGER DEFAULT 1;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS next_invoice_number INTEGER DEFAULT 1;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS postcode TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS pricing_notes TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS primary_instrument TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS secondary_instruments JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS special_offers JSONB;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS tax_number TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS theme_accent_color TEXT DEFAULT '#3B82F6';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS theme_show_terms BOOLEAN DEFAULT true;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS travel_surcharge_enabled BOOLEAN DEFAULT false;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS website TEXT;