import { useState, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Search, Filter, MoreHorizontal, DollarSign, Calendar, FileText, Download, Plus, Send, Edit, CheckCircle, AlertTriangle, Trash2, Archive, FileDown, RefreshCw, ArrowLeft } from "lucide-react";
import { insertInvoiceSchema, type Invoice } from "@shared/schema";
import { useLocation, Link } from "wouter";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { z } from "zod";
import Sidebar from "@/components/sidebar";

const invoiceFormSchema = z.object({
  contractId: z.number().optional(), // Made optional - contracts are just for auto-fill
  clientName: z.string().min(1, "Client name is required"),
  clientEmail: z.string().email("Please enter a valid email address").or(z.literal("")).optional(),
  clientAddress: z.string().optional(),
  venueAddress: z.string().optional(),
  amount: z.string().min(1, "Amount is required").refine((val) => {
    const num = parseFloat(val);
    return !isNaN(num) && num > 0;
  }, "Amount must be a valid number greater than 0"),
  dueDate: z.string().min(1, "Due date is required"),
  performanceDate: z.string().optional(),
  performanceFee: z.string().optional(),
  depositPaid: z.string().optional(),
});

export default function Invoices() {
  const { toast } = useToast();
  const [location] = useLocation();
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingInvoice, setEditingInvoice] = useState<Invoice | null>(null);
  const [editAndResendMode, setEditAndResendMode] = useState(false);
  const [selectedInvoices, setSelectedInvoices] = useState<number[]>([]);
  const [bulkActionLoading, setBulkActionLoading] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  // Check for URL parameters to auto-open dialog
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const createNew = params.get('create');
    if (createNew === 'true') {
      setIsDialogOpen(true);
    }
  }, [location]);

  const { data: invoices = [], isLoading } = useQuery({
    queryKey: ['/api/invoices'],
  });

  const { data: contracts = [] } = useQuery({
    queryKey: ['/api/contracts'],
  });

  const { data: userSettings } = useQuery({
    queryKey: ['/api/settings'],
  });

  const form = useForm<z.infer<typeof invoiceFormSchema>>({
    resolver: zodResolver(invoiceFormSchema),
    defaultValues: {
      contractId: undefined, // Optional contract selection
      clientName: "", 
      clientEmail: "",
      clientAddress: "",
      venueAddress: "",
      amount: "",
      dueDate: "",
      performanceDate: "",
      performanceFee: "",
      depositPaid: "",
    },
  });

  // Auto-set due date (invoice numbers are now auto-generated by backend)
  useEffect(() => {
    // Set due date to 30 days from now
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30);
    form.setValue("dueDate", dueDate.toISOString().split('T')[0]);
  }, [form]);

  // Watch contract ID changes
  const selectedContractId = form.watch("contractId");

  // Auto-fill fields when contract is selected (for convenience)
  useEffect(() => {
    if (selectedContractId && contracts.length > 0) {
      const selectedContract = contracts.find((c: any) => c.id === selectedContractId);
      if (selectedContract) {
        form.setValue("clientName", selectedContract.clientName);
        form.setValue("clientEmail", selectedContract.clientEmail || "");
        form.setValue("venueAddress", selectedContract.venue || "");
        if (selectedContract.eventDate) {
          form.setValue("performanceDate", new Date(selectedContract.eventDate).toISOString().split('T')[0]);
        }
        if (selectedContract.fee) {
          // Set the performance fee and calculate amount due (fee minus any deposit)
          const fee = Number(selectedContract.fee);
          const deposit = Number(selectedContract.deposit) || 0;
          const amountDue = fee - deposit;
          form.setValue("amount", amountDue.toString());
          // Store fee and deposit for backend
          form.setValue("performanceFee", fee.toString());
          form.setValue("depositPaid", deposit.toString());
        }
      }
    }
  }, [selectedContractId, contracts, form]);

  // Auto-fill business address and phone from settings
  useEffect(() => {
    if (userSettings?.businessAddress) {
      form.setValue("businessAddress", userSettings.businessAddress);
    }
    if (userSettings?.phone) {
      form.setValue("businessPhone", userSettings.phone);
    }
  }, [userSettings, form]);

  const createInvoiceMutation = useMutation({
    mutationFn: async (data: any) => {
      console.log("🔥 Frontend: Making invoice creation request");
      console.log("🔥 Frontend: Request data:", JSON.stringify(data, null, 2));
      console.log("🔥 Frontend: Request URL:", '/api/invoices');
      
      // Use fetch directly to ensure we hit the priority route
      const response = await fetch('/api/invoices', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // Important for session handling
        body: JSON.stringify(data),
      });
      
      console.log("🔥 Frontend: Response status:", response.status);
      console.log("🔥 Frontend: Response ok:", response.ok);
      
      if (!response.ok) {
        const errorData = await response.text();
        console.error("🔥 Frontend: Error response:", errorData);
        throw new Error(errorData || 'Failed to create invoice');
      }
      
      const result = await response.json();
      console.log("🔥 Frontend: Success response:", result);
      return result;
    },
    onSuccess: (data) => {
      console.log("🔥 Frontend: Mutation success:", data);
      queryClient.invalidateQueries({ queryKey: ['/api/invoices'] });
      form.reset();
      setIsDialogOpen(false);
      setEditingInvoice(null);
      toast({
        title: "Success",
        description: "Invoice created successfully!",
      });
    },
    onError: (error: any) => {
      console.error("🔥 Frontend: Mutation error:", error);
      console.error("🔥 Frontend: Error message:", error.message);
      console.error("🔥 Frontend: Error stack:", error.stack);
      
      // Show specific error message if available
      const errorMessage = error.message || "Failed to create invoice. Please try again.";
      
      toast({
        title: "Error Creating Invoice",
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  const updateInvoiceMutation = useMutation({
    mutationFn: async ({ id, data }: { id: number; data: any }) => {
      console.log("Updating invoice with data:", JSON.stringify(data, null, 2));
      const response = await apiRequest('PATCH', `/api/invoices/${id}`, data);
      if (!response.ok) {
        const errorData = await response.json();
        console.error("API Error Response:", errorData);
        throw new Error(errorData.message || 'Failed to update invoice');
      }
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/invoices'] });
      form.reset();
      setIsDialogOpen(false);
      setEditingInvoice(null);
      
      // If in edit & resend mode, automatically send the invoice
      if (editAndResendMode && editingInvoice) {
        setEditAndResendMode(false);
        setTimeout(() => {
          sendInvoiceMutation.mutate(editingInvoice);
        }, 500);
        toast({
          title: "Success",
          description: "Invoice updated and being sent...",
        });
      } else {
        toast({
          title: "Success",
          description: "Invoice updated successfully!",
        });
      }
    },
    onError: (error: any) => {
      console.error("Update invoice error:", error);
      setEditAndResendMode(false);
      
      // Show specific error message if available
      const errorMessage = error.message || "Failed to update invoice. Please try again.";
      
      toast({
        title: "Error Updating Invoice",
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  const handleEditInvoice = (invoice: Invoice) => {
    setEditingInvoice(invoice);
    setEditAndResendMode(false);
    // Pre-fill form with invoice data
    form.reset({
      contractId: invoice.contractId || undefined,
      clientName: invoice.clientName,
      clientEmail: invoice.clientEmail || "",
      clientAddress: invoice.clientAddress || "",
      venueAddress: invoice.venueAddress || "",
      amount: invoice.amount.toString(),
      dueDate: new Date(invoice.dueDate).toISOString().split('T')[0],
      performanceDate: invoice.performanceDate ? new Date(invoice.performanceDate).toISOString().split('T')[0] : "",
      performanceFee: invoice.performanceFee || "",
      depositPaid: invoice.depositPaid || "",
    });
    setIsDialogOpen(true);
  };

  const handleEditAndResend = (invoice: Invoice) => {
    setEditingInvoice(invoice);
    setEditAndResendMode(true);
    // Pre-fill form with invoice data
    form.reset({
      contractId: invoice.contractId || undefined,
      clientName: invoice.clientName,
      clientEmail: invoice.clientEmail || "",
      clientAddress: invoice.clientAddress || "",
      venueAddress: invoice.venueAddress || "",
      amount: invoice.amount.toString(),
      dueDate: new Date(invoice.dueDate).toISOString().split('T')[0],
      performanceDate: invoice.performanceDate ? new Date(invoice.performanceDate).toISOString().split('T')[0] : "",
      performanceFee: invoice.performanceFee || "",
      depositPaid: invoice.depositPaid || "",
    });
    setIsDialogOpen(true);
  };

  const onSubmit = (data: z.infer<typeof invoiceFormSchema>) => {
    console.log("Form submission data:", JSON.stringify(data, null, 2));
    console.log("Selected contract ID:", selectedContractId);
    
    // Client-side validation with user-friendly prompts
    const validationIssues = [];
    
    if (!data.clientName.trim()) {
      validationIssues.push("Client name cannot be empty");
    }
    
    if (!data.amount.trim()) {
      validationIssues.push("Amount is required");
    } else {
      const amount = parseFloat(data.amount);
      if (isNaN(amount) || amount <= 0) {
        validationIssues.push("Amount must be a valid number greater than 0");
      }
    }
    
    if (!data.dueDate) {
      validationIssues.push("Due date is required");
    }
    
    if (data.clientEmail && data.clientEmail.trim() && !data.clientEmail.includes('@')) {
      validationIssues.push("Please enter a valid email address");
    }
    
    // Show validation issues as a prompt instead of failing
    if (validationIssues.length > 0) {
      toast({
        title: "Please fix the following issues:",
        description: validationIssues.join(", "),
        variant: "destructive",
      });
      return; // Don't submit the form
    }
    
    // Warn if no client email provided
    if (!data.clientEmail || !data.clientEmail.trim()) {
      toast({
        title: "Note",
        description: "No client email provided. You won't be able to send this invoice via email until you add one.",
      });
      // Still allow creation but warn the user
    }
    
    // Send data exactly as expected by the API
    const finalData = {
      contractId: selectedContractId || null, // Can be null for standalone invoices
      // invoiceNumber is auto-generated by backend - don't send it
      clientName: data.clientName.trim(),
      clientEmail: data.clientEmail?.trim() || null,
      clientAddress: data.clientAddress?.trim() || null,
      venueAddress: data.venueAddress?.trim() || null,
      amount: data.amount.trim(),
      dueDate: data.dueDate, // Keep as string - server will convert
      performanceDate: data.performanceDate || null,
      performanceFee: data.performanceFee?.trim() || null,
      depositPaid: data.depositPaid?.trim() || null,
    };
    
    console.log("Final data being sent:", JSON.stringify(finalData, null, 2));
    
    if (editingInvoice) {
      // Update existing invoice
      updateInvoiceMutation.mutate({ id: editingInvoice.id, data: finalData });
    } else {
      // Create new invoice
      createInvoiceMutation.mutate(finalData);
    }
  };

  const handleDialogClose = () => {
    setIsDialogOpen(false);
    setEditAndResendMode(false);
    setEditingInvoice(null);
    if (window.location.search) {
      window.history.replaceState({}, document.title, window.location.pathname);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "draft": return "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300";
      case "sent": return "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300";
      case "paid": return "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300";
      case "overdue": return "bg-red-500 text-white font-bold dark:bg-red-600 dark:text-red-100";
      case "archived": return "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300";
      default: return "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300";
    }
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return "No date set";
    return new Date(dateString).toLocaleDateString("en-GB");
  };

  // Invoice action handlers
  const sendInvoiceMutation = useMutation({
    mutationFn: async (invoice: Invoice) => {
      console.log('🔥 Email Send: Starting invoice email send');
      console.log('🔥 Email Send: Invoice ID:', invoice.id);
      console.log('🔥 Email Send: Invoice data:', JSON.stringify(invoice, null, 2));
      
      // Use direct fetch to avoid middleware interference (same fix as invoice creation)
      const response = await fetch('/api/invoices/send-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // Important for session handling
        body: JSON.stringify({ invoiceId: invoice.id }),
      });
      
      console.log('🔥 Email Send: Response status:', response.status);
      console.log('🔥 Email Send: Response ok:', response.ok);
      
      if (!response.ok) {
        const errorText = await response.text();
        console.error('🔥 Email Send: Error response:', errorText);
        throw new Error(errorText || 'Failed to send invoice email');
      }
      
      const result = await response.json();
      console.log('🔥 Email Send: Success response:', result);
      return result;
    },
    onSuccess: () => {
      console.log('🔥 Email Send: SUCCESS');
      queryClient.invalidateQueries({ queryKey: ['/api/invoices'] });
      toast({
        title: "Success",
        description: "Invoice sent successfully with view link!",
      });
    },
    onError: (error: any) => {
      console.error('🔥 Email Send: ERROR');
      console.error('🔥 Email Send: Full error object:', error);
      console.error('🔥 Email Send: Error message:', error.message);
      console.error('🔥 Email Send: Error stack:', error.stack);
      toast({
        title: "Error",
        description: `Failed to send invoice email: ${error.message}`,
        variant: "destructive",
      });
    },
  });

  const handleSendInvoice = (invoice: Invoice) => {
    console.log('=== INVOICE SEND DEBUG ===');
    console.log('Invoice ID:', invoice.id);
    console.log('Invoice data:', invoice);
    console.log('Authentication check - making request...');
    
    // Add visual feedback
    toast({
      title: "Sending Invoice...",
      description: `Sending invoice ${invoice.invoiceNumber} with view link to ${invoice.clientEmail || 'client'}`,
    });
    
    sendInvoiceMutation.mutate(invoice);
  };

  // Mark invoice as paid mutation
  const markPaidMutation = useMutation({
    mutationFn: async (invoice: Invoice) => {
      const response = await apiRequest('POST', `/api/invoices/${invoice.id}/mark-paid`, {});
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/invoices'] });
      toast({
        title: "Success",
        description: "Invoice marked as paid successfully!",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to mark invoice as paid",
        variant: "destructive",
      });
    },
  });

  // Send overdue reminder mutation
  const sendReminderMutation = useMutation({
    mutationFn: async (invoice: Invoice) => {
      const response = await apiRequest('POST', `/api/invoices/${invoice.id}/send-reminder`, {});
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Overdue reminder sent successfully!",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to send overdue reminder",
        variant: "destructive",
      });
    },
  });

  const handleMarkAsPaid = (invoice: Invoice) => {
    markPaidMutation.mutate(invoice);
  };

  const handleSendReminder = (invoice: Invoice) => {
    sendReminderMutation.mutate(invoice);
  };

  // Resend invoice mutation
  const resendInvoiceMutation = useMutation({
    mutationFn: async (invoice: Invoice) => {
      console.log('Resending invoice:', invoice.id);
      const response = await apiRequest('POST', '/api/invoices/send-email', { invoiceId: invoice.id });
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Invoice resent successfully!",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to resend invoice",
        variant: "destructive",
      });
    },
  });

  const handleResendInvoice = (invoice: Invoice) => {
    resendInvoiceMutation.mutate(invoice);
  };

  // Restore archived invoice mutation
  const restoreInvoiceMutation = useMutation({
    mutationFn: async (invoice: Invoice) => {
      const response = await apiRequest('PATCH', `/api/invoices/${invoice.id}`, { status: "draft" });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      toast({
        title: "Success",
        description: "Invoice restored from archive successfully!",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to restore invoice",
        variant: "destructive",
      });
    },
  });

  const handleRestoreInvoice = (invoice: Invoice) => {
    restoreInvoiceMutation.mutate(invoice);
  };

  // Bulk action handlers
  const handleSelectInvoice = (invoiceId: number, checked: boolean) => {
    if (checked) {
      setSelectedInvoices(prev => [...prev, invoiceId]);
    } else {
      setSelectedInvoices(prev => prev.filter(id => id !== invoiceId));
    }
  };

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedInvoices(filteredInvoices.map(invoice => invoice.id));
    } else {
      setSelectedInvoices([]);
    }
  };

  const deleteMutation = useMutation({
    mutationFn: async (invoiceIds: number[]) => {
      const responses = await Promise.all(
        invoiceIds.map(id => 
          apiRequest('DELETE', `/api/invoices/${id}`, {})
        )
      );
      return responses;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      setSelectedInvoices([]);
      toast({
        title: "Invoices deleted",
        description: `${selectedInvoices.length} invoice(s) deleted successfully`,
      });
    },
    onError: () => {
      toast({
        title: "Error deleting invoices",
        description: "Failed to delete selected invoices",
        variant: "destructive",
      });
    },
  });

  const archiveMutation = useMutation({
    mutationFn: async (invoiceIds: number[]) => {
      const responses = await Promise.all(
        invoiceIds.map(id => 
          apiRequest('PATCH', `/api/invoices/${id}`, { status: "archived" })
        )
      );
      return responses;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      setSelectedInvoices([]);
      toast({
        title: "Invoices archived",
        description: `${selectedInvoices.length} invoice(s) archived successfully`,
      });
    },
    onError: () => {
      toast({
        title: "Error archiving invoices",
        description: "Failed to archive selected invoices",
        variant: "destructive",
      });
    },
  });

  // Bulk restore mutation
  const bulkRestoreMutation = useMutation({
    mutationFn: async (invoiceIds: number[]) => {
      const responses = await Promise.all(
        invoiceIds.map(id => 
          apiRequest("PATCH", `/api/invoices/${id}`, { status: "draft" })
        )
      );
      return responses;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/invoices"] });
      setSelectedInvoices([]);
      toast({
        title: "Invoices restored",
        description: `${selectedInvoices.length} invoice(s) restored from archive successfully`,
      });
    },
    onError: () => {
      toast({
        title: "Error restoring invoices",
        description: "Failed to restore selected invoices",
        variant: "destructive",
      });
    },
  });

  const handleBulkAction = async (action: string) => {
    if (selectedInvoices.length === 0) return;
    
    setBulkActionLoading(true);
    
    try {
      switch (action) {
        case 'delete':
          await deleteMutation.mutateAsync(selectedInvoices);
          break;
        case 'archive':
          await archiveMutation.mutateAsync(selectedInvoices);
          break;
        case 'restore':
          await bulkRestoreMutation.mutateAsync(selectedInvoices);
          break;
        case 'download':
          // Download each selected invoice
          for (const invoiceId of selectedInvoices) {
            window.open(`/api/invoices/${invoiceId}/pdf`, '_blank');
          }
          setSelectedInvoices([]);
          toast({
            title: "Downloads started",
            description: `Downloading ${selectedInvoices.length} invoice(s)`,
          });
          break;
      }
    } catch (error) {
      console.error('Bulk action error:', error);
    } finally {
      setBulkActionLoading(false);
    }
  };

  const handleDownloadInvoice = async (invoice: Invoice) => {
    try {
      const response = await fetch(`/api/invoices/${invoice.id}/pdf`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Invoice-${invoice.invoiceNumber}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
      
      toast({
        title: "Success",
        description: "Invoice PDF downloaded successfully!",
      });
    } catch (error) {
      console.error('Error downloading invoice:', error);
      toast({
        title: "Error",
        description: "Failed to download invoice PDF",
        variant: "destructive",
      });
    }
  };

  const filteredInvoices = invoices.filter((invoice: Invoice) => {
    const matchesSearch = searchQuery === "" || 
      invoice.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
      invoice.clientName.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesStatus = statusFilter === "all" || invoice.status === statusFilter;
    
    return matchesSearch && matchesStatus;
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 rounded w-1/4"></div>
          <div className="space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-32 bg-gray-200 rounded"></div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      
      {/* Main Content */}
      <div className="md:ml-64">
        {/* Header */}
        <div className="bg-white border-b border-gray-200 px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <button
                onClick={() => setSidebarOpen(!sidebarOpen)}
                className="md:hidden mr-3 p-2 rounded-md hover:bg-gray-100"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Invoices</h1>
                <p className="text-gray-600">Manage your invoices and payments</p>
              </div>
            </div>
            <div className="flex gap-3">
              <Dialog open={isDialogOpen} onOpenChange={(open) => {
              setIsDialogOpen(open);
              if (!open) {
                setEditingInvoice(null);
                form.reset();
              }
            }}>
              <DialogTrigger asChild>
                <Button>
                  <Plus className="w-4 h-4 mr-2" />
                  Create Invoice
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>
                    {editAndResendMode ? "Edit Invoice & Resend" : editingInvoice ? "Edit Invoice" : "Create New Invoice"}
                  </DialogTitle>
                  {editAndResendMode && (
                    <p className="text-sm text-gray-600 mt-2">
                      Invoice number {editingInvoice?.invoiceNumber} will remain unchanged for tax compliance.
                    </p>
                  )}
                </DialogHeader>
                <Form {...form}>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                    <div className="grid grid-cols-2 gap-4">

                      <FormField
                        control={form.control}
                        name="contractId"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Select Contract (optional - for auto-fill)</FormLabel>
                            <Select 
                              value={field.value?.toString()} 
                              onValueChange={(value) => field.onChange(parseInt(value))}
                            >
                              <FormControl>
                                <SelectTrigger>
                                  <SelectValue placeholder="Choose a contract to auto-fill fields" />
                                </SelectTrigger>
                              </FormControl>
                              <SelectContent>
                                {contracts.map((contract: any) => (
                                  <SelectItem key={contract.id} value={contract.id.toString()}>
                                    <div className="flex items-center justify-between w-full">
                                      <span>{contract.clientName} - {formatDate(contract.eventDate)}</span>
                                      {!contract.clientEmail && (
                                        <span className="text-xs text-red-500 ml-2">⚠ No email</span>
                                      )}
                                    </div>
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <FormField
                      control={form.control}
                      name="clientName"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Client Name</FormLabel>
                          <FormControl>
                            <Input placeholder="Client name" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="clientEmail"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Client Email</FormLabel>
                          <FormControl>
                            <Input type="email" placeholder="client@example.com" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <div className="grid grid-cols-2 gap-4">
                      <FormField
                        control={form.control}
                        name="clientAddress"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Client Address</FormLabel>
                            <FormControl>
                              <Input placeholder="Client's address" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      <FormField
                        control={form.control}
                        name="venueAddress"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Venue Address</FormLabel>
                            <FormControl>
                              <Input placeholder="Performance venue address" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-3 gap-4">
                      <FormField
                        control={form.control}
                        name="amount"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Amount (£)</FormLabel>
                            <FormControl>
                              <Input placeholder="500.00" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      <FormField
                        control={form.control}
                        name="dueDate"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Due Date</FormLabel>
                            <FormControl>
                              <Input type="date" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      <FormField
                        control={form.control}
                        name="performanceDate"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Performance Date</FormLabel>
                            <FormControl>
                              <Input type="date" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="flex justify-end gap-3">
                      <Button type="button" variant="outline" onClick={handleDialogClose}>
                        Cancel
                      </Button>
                      <Button type="submit" disabled={createInvoiceMutation.isPending}>
                        {createInvoiceMutation.isPending ? "Creating..." : "Create Invoice"}
                      </Button>
                    </div>
                  </form>
                </Form>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="p-6">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 mb-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 dark:text-gray-500 w-4 h-4" />
              <Input
                placeholder="Search by invoice number or client name..."
                className="pl-10"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-full md:w-48">
                <Filter className="w-4 h-4 mr-2" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Statuses</SelectItem>
                <SelectItem value="draft">Draft</SelectItem>
                <SelectItem value="sent">Sent</SelectItem>
                <SelectItem value="paid">Paid</SelectItem>
                <SelectItem value="overdue">Overdue</SelectItem>
                <SelectItem value="archived">Archived</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-300">Outstanding</p>
                  <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                    £{invoices.filter((inv: Invoice) => inv.status === "sent").reduce((sum: number, inv: Invoice) => sum + Number(inv.amount), 0).toLocaleString()}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    {invoices.filter((inv: Invoice) => inv.status === "sent").length} invoices
                  </p>
                </div>
                <FileText className="w-8 h-8 text-blue-600 dark:text-blue-400" />
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-300">Overdue</p>
                  <p className="text-2xl font-bold text-red-600 dark:text-red-400">
                    {invoices.filter((inv: Invoice) => inv.status === "overdue").length}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Need attention</p>
                </div>
                <Calendar className="w-8 h-8 text-red-600 dark:text-red-400" />
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-300">Paid This Month</p>
                  <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                    £{invoices.filter((inv: Invoice) => inv.status === "paid").reduce((sum: number, inv: Invoice) => sum + Number(inv.amount), 0).toLocaleString()}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Great progress!</p>
                </div>
                <DollarSign className="w-8 h-8 text-green-600 dark:text-green-400" />
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-300">Total Invoices</p>
                  <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">{invoices.length}</p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">All time</p>
                </div>
                <FileText className="w-8 h-8 text-gray-600 dark:text-gray-400" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Bulk Actions Bar */}
        {selectedInvoices.length > 0 && (
          <Card className="mb-4 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <span className="text-sm font-medium text-blue-900 dark:text-blue-100">
                    {selectedInvoices.length} invoice(s) selected
                  </span>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => setSelectedInvoices([])}
                  >
                    Clear Selection
                  </Button>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleBulkAction('download')}
                    disabled={bulkActionLoading}
                  >
                    <FileDown className="w-4 h-4 mr-1" />
                    Download PDFs
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleBulkAction('archive')}
                    disabled={bulkActionLoading}
                  >
                    <Archive className="w-4 h-4 mr-1" />
                    Archive
                  </Button>
                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => handleBulkAction('delete')}
                    disabled={bulkActionLoading}
                  >
                    <Trash2 className="w-4 h-4 mr-1" />
                    Delete
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Invoices List */}
        <div className="space-y-4">
          {filteredInvoices.length === 0 ? (
            <Card>
              <CardContent className="p-12 text-center">
                <FileText className="w-12 h-12 text-gray-400 dark:text-gray-500 mx-auto mb-4" />
                <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">No invoices found</h3>
                <p className="text-gray-600 dark:text-gray-300 mb-4">
                  {searchQuery || statusFilter !== "all" 
                    ? "Try adjusting your search or filter criteria."
                    : "Get started by creating your first invoice."
                  }
                </p>
                <Button onClick={() => setIsDialogOpen(true)}>
                  <Plus className="w-4 h-4 mr-2" />
                  Create Invoice
                </Button>
              </CardContent>
            </Card>
          ) : (
            <>
              {/* Select All Checkbox */}
              {filteredInvoices.length > 0 && (
                <Card className="mb-4">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-3">
                      <input
                        type="checkbox"
                        checked={selectedInvoices.length === filteredInvoices.length && filteredInvoices.length > 0}
                        onChange={(e) => handleSelectAll(e.target.checked)}
                        className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                      />
                      <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                        Select All ({filteredInvoices.length} invoices)
                      </span>
                    </div>
                  </CardContent>
                </Card>
              )}
              
              {filteredInvoices.map((invoice: Invoice) => {
                const isSelected = selectedInvoices.includes(invoice.id);
                return (
                  <Card key={invoice.id} className={`hover:shadow-md transition-shadow ${isSelected ? 'ring-2 ring-blue-500 bg-blue-50 dark:bg-blue-900/20' : ''}`}>
                    <CardContent className="p-6">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <input
                            type="checkbox"
                            checked={isSelected}
                            onChange={(e) => handleSelectInvoice(invoice.id, e.target.checked)}
                            className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                          />
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                          <h3 className="font-semibold text-lg text-gray-900 dark:text-gray-100">
                            Invoice #{invoice.invoiceNumber}
                          </h3>
                          <Badge className={getStatusColor(invoice.status)}>
                            {invoice.status}
                          </Badge>
                        </div>
                        
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-gray-600 dark:text-gray-300">
                          <div>
                            <span className="font-medium">Client:</span>
                            <p className="text-gray-900 dark:text-gray-100">{invoice.clientName}</p>
                          </div>
                          <div>
                            <span className="font-medium">Amount:</span>
                            <p className="text-gray-900 dark:text-gray-100 font-semibold">£{Number(invoice.amount).toLocaleString()}</p>
                          </div>
                          <div>
                            <span className="font-medium">Due Date:</span>
                            <p className="text-gray-900 dark:text-gray-100">{formatDate(invoice.dueDate)}</p>
                          </div>
                          <div>
                            <span className="font-medium">Created:</span>
                            <p className="text-gray-900 dark:text-gray-100">{formatDate(invoice.createdAt!)}</p>
                          </div>
                            </div>
                          </div>
                        </div>
                      
                      <div className="flex items-center gap-2 ml-4">
                        {invoice.status === "draft" && (
                          <>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs"
                              onClick={() => handleEditInvoice(invoice)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              Edit
                            </Button>
                            <Button 
                              size="sm" 
                              className="text-xs" 
                              onClick={() => handleSendInvoice(invoice)}
                              disabled={sendInvoiceMutation.isPending}
                            >
                              <Send className="w-3 h-3 mr-1" />
                              {sendInvoiceMutation.isPending ? 'Sending...' : 'Send'}
                            </Button>
                          </>
                        )}
                        
                        {invoice.status === "sent" && (
                          <>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-green-600 hover:text-green-700" 
                              onClick={() => handleMarkAsPaid(invoice)}
                              disabled={markPaidMutation.isPending}
                            >
                              <CheckCircle className="w-3 h-3 mr-1" />
                              Mark Paid
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-blue-600 hover:text-blue-700" 
                              onClick={() => handleResendInvoice(invoice)}
                              disabled={resendInvoiceMutation.isPending}
                            >
                              <RefreshCw className="w-3 h-3 mr-1" />
                              Resend
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-purple-600 hover:text-purple-700" 
                              onClick={() => handleEditAndResend(invoice)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              Edit & Resend
                            </Button>
                            <Button size="sm" variant="outline" className="text-xs" onClick={() => handleDownloadInvoice(invoice)}>
                              <Download className="w-3 h-3 mr-1" />
                              Download
                            </Button>
                          </>
                        )}
                        
                        {invoice.status === "overdue" && (
                          <>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-green-600 hover:text-green-700" 
                              onClick={() => handleMarkAsPaid(invoice)}
                              disabled={markPaidMutation.isPending}
                            >
                              <CheckCircle className="w-3 h-3 mr-1" />
                              Mark Paid
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-blue-600 hover:text-blue-700" 
                              onClick={() => handleResendInvoice(invoice)}
                              disabled={resendInvoiceMutation.isPending}
                            >
                              <RefreshCw className="w-3 h-3 mr-1" />
                              Resend
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-purple-600 hover:text-purple-700" 
                              onClick={() => handleEditAndResend(invoice)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              Edit & Resend
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-red-600 hover:text-red-700" 
                              onClick={() => handleSendReminder(invoice)}
                              disabled={sendReminderMutation.isPending}
                            >
                              <AlertTriangle className="w-3 h-3 mr-1" />
                              Overdue Notice
                            </Button>
                            <Button size="sm" variant="outline" className="text-xs" onClick={() => handleDownloadInvoice(invoice)}>
                              <Download className="w-3 h-3 mr-1" />
                              Download
                            </Button>
                          </>
                        )}
                        
                        {invoice.status === "paid" && (
                          <>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-blue-600 hover:text-blue-700" 
                              onClick={() => handleResendInvoice(invoice)}
                              disabled={resendInvoiceMutation.isPending}
                            >
                              <RefreshCw className="w-3 h-3 mr-1" />
                              Resend Copy
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-purple-600 hover:text-purple-700" 
                              onClick={() => handleEditAndResend(invoice)}
                            >
                              <Edit className="w-3 h-3 mr-1" />
                              Edit & Resend
                            </Button>
                            <Button size="sm" variant="outline" className="text-xs" onClick={() => handleDownloadInvoice(invoice)}>
                              <Download className="w-3 h-3 mr-1" />
                              Download
                            </Button>
                          </>
                        )}

                        {invoice.status === "archived" && (
                          <>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="text-xs text-green-600 hover:text-green-700" 
                              onClick={() => handleRestoreInvoice(invoice)}
                              disabled={restoreInvoiceMutation.isPending}
                            >
                              <RefreshCw className="w-3 h-3 mr-1" />
                              Restore
                            </Button>
                            <Button size="sm" variant="outline" className="text-xs" onClick={() => handleDownloadInvoice(invoice)}>
                              <Download className="w-3 h-3 mr-1" />
                              Download
                            </Button>
                          </>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
                );
              })}
            </>
          )}
        </div>
      </div>
      </div>
    </div>
  );
}